name: color_pool_puzzle
description: Ball puzzle game with walls and holes
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0" # Для Flutter 3.19.6 лучше ограничить верхнюю границу: ">=3.0.0 <3.20.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2 # Версия 2.5.4 может требовать новый SDK, для 3.19.6 лучше 2.2.x
  audioplayers: ^5.2.1       # Версия 6.x может иметь проблемы на старом web, 5.x стабильнее
  vibration: ^1.8.4          # Проверьте совместимость, для web часто нужны полифилы
  provider: ^6.1.2
  intl: ^0.18.1              # Совместимо с SDK 3.0-3.19
  package_info_plus: ^5.0.1  # Совместимо с SDK 3.0-3.19
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/fonts/Roboto/ # <-- Добавляем папку шрифтов в assets

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700