name: color_pool_puzzle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  http: any
  ui:
    path: packages/ui
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  intl: any
  supabase_flutter: ^2.10.3
  flutter_dotenv: ^6.0.0   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/icon_settings.json
    - .env
